name: Release Please

on:
  push:
    branches:
      - ci/publish

permissions:
  contents: write
  pull-requests: write

jobs:
  # release-please:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     release_created: ${{ steps.release.outputs.release_created }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: oven-sh/setup-bun@v2
  #     - run: bun install
  #     - run: bun test
  #     - run: bun lint
  #     - uses: googleapis/release-please-action@v4
  #       id: release
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    # needs: release-please
    # if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: read
      id-token: write
    environment:
      name: NPM Registry
      url: https://www.npmjs.com/package/${{ steps.package.outputs.NAME }}/v/${{ steps.package.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - run: npm version patch --no-git-tag-version
      - id: package
        run: |
          jq -r '"NAME=" + .name' package.json >> "$GITHUB_OUTPUT"
          jq -r '"VERSION=" + .version' package.json >> "$GITHUB_OUTPUT"
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
